name: Deploy con SSH por ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar rsync
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Agregar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 12345 4.tcp.ngrok.io >> ~/.ssh/known_hosts

      - name: Deploy con rsync
        run: |
          rsync -avz -e "ssh -p 12345 -o StrictHostKeyChecking=yes" ./ estebancalcagno@4.tcp.ngrok.io:/home/estebancalcagno/sitios/mi-web-cicd
