name: Despliegue automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Agregar clave SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copiar archivos al servidor
        run: |
          rsync -avz --delete ./ estebancalcagno@192.168.0.16:/Users/estebancalcagno/sitios/mi-web-cicd
